language: android
android:
  components:
  # from app build file
    - build-tools-26.0.0
    - android-26
  licenses:
    - '.+'

#make gradlew executable on travis
before_script:
  - chmod +x gradlew

#override default script to exclude emulator
script:
  - ./gradlew build check